### ISSUE TITLE
InflateExeption

### ISSUE THREAD

**Issue by mr-sarsarabi** [iammert/AnimatedTabLayout#5]
I get this Inflate Exception on the Animated Tab Layout xml. how can i fix it?
I'm trying to use this in Java.
```ava.lang.RuntimeException: Unable to start activity ComponentInfo{info.touchstudio.iot/info.touchstudio.iot.Activities.LeaderBoardActivity}: android.view.InflateException: Binary XML file line #88: Binary XML file line #88: Error inflating class com.iammert.library.AnimatedTabLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3184)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3292)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7415)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #88: Binary XML file line #88: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: android.view.InflateException: Binary XML file line #88: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at info.touchstudio.iot.Activities.LeaderBoardActivity.onCreate(LeaderBoardActivity.java:15)
        at android.app.Activity.performCreate(Activity.java:7373)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3292)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7415)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:270)
        at android.content.res.Resources.getDimension(Resources.java:720)
        at com.iammert.library.AnimatedTabResourceParser.getDimen(AnimatedTabResourceParser.kt:73)
        at com.iammert.library.AnimatedTabResourceParser.parseTabsConfig(AnimatedTabResourceParser.kt:40)
        at com.iammert.library.AnimatedTabResourceParser.parse(AnimatedTabResourceParser.kt:23)
        at com.iammert.library.AnimatedTabLayout.init(AnimatedTabLayout.kt:52)
        at com.iammert.library.AnimatedTabLayout.<init>(AnimatedTabLayout.kt:35)
        	... 34 more```

**Comment by Etio39** [comment]
Got the same problem, did you find a solution ?

**Comment by ghorbanzadeh-me** [comment]
I have the same problem . Anyone can help us ?

**Comment by Smarpit-Singh** [comment]
I also got the same problem

    
    Process: com.jsrsotutions.ecomm, PID: 5768
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jsrsotutions.ecomm/com.jsrsotutions.ecomm.ui.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #32: Error inflating class com.iammert.library.AnimatedTabLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #32: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.jsrsotutions.ecomm.ui.MainActivity.onCreate(MainActivity.java:41)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
        at android.content.res.Resources.getDimension(Resources.java:597)
        at com.iammert.library.AnimatedTabResourceParser.getDimen(AnimatedTabResourceParser.kt:73)
        at
     com.iammert.library.AnimatedTabResourceParser.parseTabsConfig(AnimatedTabResourceParser.kt:40)
        at com.iammert.library.AnimatedTabResourceParser.parse(AnimatedTabResourceParser.kt:23)
        at com.iammert.library.AnimatedTabLayout.init(AnimatedTabLayout.kt:52)
       2019-02-20 13:18:50.474 5768-5768/com.jsrsotutions.ecomm E/AndroidRuntime:     at 
       com.iammert.library.AnimatedTabLayout.<init>(AnimatedTabLayout.kt:35)
        	... 30 more

**Comment by MarsadMaqsood** [comment]
I'm facing the same problem

```
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.marsad.chatapp/com.marsad.chatapp.MainActivity}: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.iammert.library.AnimatedTabLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3178)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3313)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7139)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: android.view.InflateException: Binary XML file line #42: Binary XML file line #42: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: android.view.InflateException: Binary XML file line #42: Error inflating class com.iammert.library.AnimatedTabLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:908)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.marsad.chatapp.MainActivity.onCreate(MainActivity.java:65)
        at android.app.Activity.performCreate(Activity.java:7268)
        at android.app.Activity.performCreate(Activity.java:7259)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3158)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3313)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7139)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:246)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2256)
        at android.content.res.Resources.getXml(Resources.java:1279)
        at com.iammert.library.AnimatedTabResourceParser.<init>(AnimatedTabResourceParser.kt:11)
        at com.iammert.library.AnimatedTabLayout.init(AnimatedTabLayout.kt:52)
2020-06-14 19:39:10.124 31323-31323/? E/AndroidRuntime:     at com.iammert.library.AnimatedTabLayout.<init>(AnimatedTabLayout.kt:35)
```
